### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [TouaregWarrior/MMM-MortgageCountdown#1]
Thanks for this module! :slightly_smiling_face: 

It would be nice if you could add the screenshot into your repository. Then it will be used in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/).

**Comment by TouaregWarrior** [comment]
Screen grab added! 
MMM-MortgageCountdown.png

**Comment by KristjanESPERANTO** [comment]
Nice! Now your module looks better on the new list :slightly_smiling_face:
